# Generated by Django 5.0.6 on 2026-07-17 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_signature_id', models.CharField(max_length=100)),
                ('signing_url', models.URLField(blank=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pagare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_firma', to='pagares.pagare')),
            ],
        ),
    ]
