# Generated by Django 5.0.6 on 2026-07-17 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pagare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('beneficiario', models.CharField(max_length=200, verbose_name='Nombre de la persona a quien ha de pagarse')),
                ('lugar_expedicion', models.CharField(max_length=150)),
                ('fecha_expedicion', models.DateField()),
                ('lugar_pago', models.CharField(max_length=150)),
                ('fecha_pago', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_en_letra', models.CharField(max_length=255)),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADO', 'PDF generado'), ('ENVIADO_FIRMA', 'Enviado a firma electrónica'), ('FIRMADO', 'Firmado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pagares_pdf/')),
                ('hash_documento', models.CharField(blank=True, help_text='SHA-256 del PDF generado, para verificar integridad.', max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagares', to=settings.AUTH_USER_MODEL)),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagares', to='pagares.cliente')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
