# Generated by Django 5.0.6 on 2026-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-creado_en'],
            },
        ),
    ]
